name: Manual Trigger for Azure ML Job

on:
  push:
    branches:
      - master

jobs:
  trigger-aml-job:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Checkout du code
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Télécharger tout le dépôt

    # Étape 2 : Lister les répertoires pour vérifier la structure
    - name: List directory contents
      run: |
        ls -R ./  # Liste récursive de tout le contenu du projet

    # Étape 3 : Connexion à Azure CLI avec le Service Principal existant
    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Étape 4 : Installer l'extension Azure ML CLI
    - name: Install Azure ML CLI extension
      run: |
        az extension add --name ml -y
        az configure --defaults workspace=${{ secrets.AML_WORKSPACE }} group=${{ secrets.RESOURCE_GROUP }}

    # Étape 5 : Soumission du job Azure ML
    - name: Submit Azure ML job
      run: |
        az ml job create --file ./job-definition.yml \
        --resource-group ${{ secrets.RESOURCE_GROUP }} \
        --workspace-name ${{ secrets.AML_WORKSPACE }}

    - name: Placeholder
      run: |
        echo "Will add code checks here in next challenge"