name: Manual Trigger for Azure ML Job

on:
  workflow_dispatch:

jobs:
  trigger-aml-job:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Checkout du code
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Connexion à Azure CLI
    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Étape 3 : Installation de l'extension Azure ML CLI
    - name: Install Azure ML CLI extension
      run: |
        az extension add --name ml -y
        az configure --defaults workspace=${{ secrets.AML_WORKSPACE }} group=${{ secrets.RESOURCE_GROUP }}

    # Étape 4 : Soumission du job Azure ML
    - name: Submit Azure ML job
      run: |
        az ml job create --file ./yaml/job-definition.yml --resource-group ${{ secrets.RESOURCE_GROUP }} --workspace-name ${{ secrets.AML_WORKSPACE }}
