name: Manual Trigger for Azure ML Job

on:
  workflow_dispatch:

jobs:
  trigger-aml-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Télécharger tout le dépôt

    - name: List directory contents
      run: |
        ls -R ./  # Liste récursive de tout le contenu du projet pour vérifier la présence de diabetes-dev.csv

    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install Azure ML CLI extension
      run: |
        az extension add --name ml -y
        az configure --defaults workspace=${{ secrets.AML_WORKSPACE }} group=${{ secrets.RESOURCE_GROUP }}

    - name: Submit Azure ML job
      run: |
        az ml job create --file ./yaml/job-definition.yml